const kGLTokenValue =
    'eyJhbGciOiJIUzM4NCIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3Mjc4MDEyNzcsImV4cCI6MTcyNzgwODQ3NywiaXNzIjoic3RhZ2UuZ3JlZW5saWdodC5nbC10ZWNoLmlvL2lkZW50aXR5IiwiYXVkIjoicGFydG5lcnMuZ2wtdGVjaC5pbyIsInN1YiI6IjIwNTMyOTQwIiwiYWN0Ijp7InN1YiI6ImlvLmdsLXRlY2gucGFydG5lcnMvVlNDVSJ9fQ.l_WjMq2hmoO6WnxKhKQynEv--hyJtkeQz3wciOEesBUf2VPK8kz-SGyFuFxRUSsb';
const kGLTokenExpiresIn = 3600;
const kGLTokenType = 'Bearer';
